name: Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.NOTIFY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/Style-Forge/hub/dispatches \
            -d '{"event_type":"update-style-forge", "client_payload": {"package_name": "style-forge.base"}}'
